version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hb-bank-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=production
    restart: always
